import requests
 
def CHECKGTM(url):
   
    r = requests.get(url)
    htmlBody = str(r.content)
    if htmlBody.find('GTM-NH8V9ZX') != -1:
        print(url+"|GTM FOUND")
       
    else:
        print(url+"|GTM not found")
        # print("*********************************\n")

f = ["https://www.tamaslim.com",
"https://www.tamaslim.com/contact/",
"https://www.tamaslim.com/articles/",
"https://www.tamaslim.com/cdn-cgi/l/email-protection",
"https://www.tamaslim.com/careers/",
"https://www.tamaslim.com/sit-to-fit/",
"https://www.tamaslim.com/docs/terms.html"]

for x in f:
    CHECKGTM(x)





# https://www.tamaslim.com

# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/contact/
# 200
# HPLNK
# https://www.tamaslim.com/careers/
# Contact	
# text
# —	
# DF
# https://www.tamaslim.com/contact/
# 200
# HPLNK
# https://www.tamaslim.com/sit-to-fit/
# Contact	
# text
# —	
# DF
# https://www.tamaslim.com/articles/
# 200
# HPLNK
# https://www.tamaslim.com/
# Articles	
# text
# —	
# DF
# https://www.tamaslim.com/articles/
# 200
# HPLNK
# https://www.tamaslim.com
# Articles	
# text
# —	
# DF
# https://www.tamaslim.com/articles/
# 200
# HPLNK
# https://www.tamaslim.com/contact/
# Articles	
# text
# —	
# DF
# https://www.tamaslim.com/articles/
# 200
# HPLNK
# https://www.tamaslim.com/careers/
# Articles	
# text
# —	
# DF
# https://www.tamaslim.com/articles/
# 200
# HPLNK
# https://www.tamaslim.com/sit-to-fit/
# Articles	
# text
# —	
# DF
# https://www.tamaslim.com/cdn-cgi/l/email-protection
# 200
# HPLNK
# https://www.tamaslim.com/contact/
# [email protected]	
# text
# —	
# DF
# https://www.tamaslim.com/cdn-cgi/l/email-protection
# 200
# HPLNK
# https://www.tamaslim.com/careers/
# [email protected]	
# text
# —	
# DF
# https://www.tamaslim.com/cdn-cgi/l/email-protection
# 200
# HPLNK
# https://www.tamaslim.com/sit-to-fit/
# [email protected]	
# text
# —	
# DF
# https://www.tamaslim.com/careers/
# 200
# HPLNK
# https://www.tamaslim.com/
# Careers	
# text
# —	
# DF
# https://www.tamaslim.com/careers/
# 200
# HPLNK
# https://www.tamaslim.com
# Careers	
# text
# —	
# DF
# https://www.tamaslim.com/careers/
# 200
# HPLNK
# https://www.tamaslim.com/contact/
# Careers	
# text
# —	
# DF
# https://www.tamaslim.com/careers/
# 200
# HPLNK
# https://www.tamaslim.com/articles/
# Careers	
# text
# —	
# DF
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/docs/terms.html
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/
# https://www.tamaslim.com
# https://www.tamaslim.com/images/logo.png?ver=1121366
# https://www.tamaslim.com/
# https://www.tamaslim.com/images/logo.png?ver=1121366
# https://www.tamaslim.com
# https://www.tamaslim.com/images/logo.png?ver=1121366
# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/images/logo.png?ver=1121366
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/images/logo.png?ver=1121366
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/images/logo.png?ver=1121366
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/images/tamaslim-1-bottle.png?ver=1.1
# https://www.tamaslim.com/
# https://www.tamaslim.com
# https://www.tamaslim.com/images/cut-cravings-icon.png
# https://www.tamaslim.com/
# https://www.tamaslim.com/images/cut-cravings-icon.png
# https://www.tamaslim.com
# https://www.tamaslim.com/images/boost-metabolism-icon.png
# https://www.tamaslim.com/
# https://www.tamaslim.com
# https://www.tamaslim.com/images/garcinia-cambogia-rounded-bg-item.png?ver=1.1
# https://www.tamaslim.com/
# https://www.tamaslim.com/images/garcinia-cambogia-rounded-bg-item.png?ver=1.1
# https://www.tamaslim.com
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/images/healthy-eating-made-simple.jpg
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/images/1-bottle.png?ver=1.1
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/images/shipping-truck-big.png
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/images/6-bottles.png?ver=1.1
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/images/sound.svg
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/images/3-bottles.png?ver=1.1
# 200
# IMG
# https://www.tamaslim.com/sit-to-fit/
# —	
# —
# —	
# DF
# https://www.tamaslim.com/css/font-awesome.min.css
# 200
# CSS
# https://www.tamaslim.com/
# —	
# —
# —	
# DF
# https://www.tamaslim.com/css/font-awesome.min.css
# 200
# CSS
# https://www.tamaslim.com
# —	
# —
# —	
# DF
# https://www.tamaslim.com/css/font-awesome.min.css
# 200
# CSS
# https://www.tamaslim.com/contact/
# —	
# —
# —	
# DF
# https://www.tamaslim.com/css/font-awesome.min.css
# 200
# CSS
# https://www.tamaslim.com/articles/
# —	
# —
# —	
# DF
# https://www.tamaslim.com/css/font-awesome.min.css
# 200
# CSS
# https://www.tamaslim.com/careers/
# —	
# —
# —	
# DF
# https://www.tamaslim.com/css/font-awesome.min.css
# 200
# CSS
# https://www.tamaslim.com/sit-to-fit/
# —	
# —
# —	
# DF
# https://www.tamaslim.com/css/bootstrap.min.css
# https://www.tamaslim.com/
# https://www.tamaslim.com/css/bootstrap.min.css
# https://www.tamaslim.com
# https://www.tamaslim.com/css/bootstrap.min.css
# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/css/bootstrap.min.css
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/css/bootstrap.min.css
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/css/bootstrap.min.css
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/css/app.css?v14:33:59
# https://www.tamaslim.com/
# https://www.tamaslim.com/css/app.css?v14:34:00
# https://www.tamaslim.com
# https://www.tamaslim.com/css/app.css?v14:34:00
# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/css/app.css?v14:34:00
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/css/app.css?v14:34:01
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/css/app.css?v14:34:01
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/cdn-cgi/styles/cf.errors.css
# https://www.tamaslim.com/cdn-cgi/l/email-protection
# https://www.tamaslim.com/js/bootstrap.min.js
# https://www.tamaslim.com/
# https://www.tamaslim.com/js/bootstrap.min.js
# https://www.tamaslim.com
# https://www.tamaslim.com/js/bootstrap.min.js
# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/js/bootstrap.min.js
# https://www.tamaslim.com/articles/
# https://www.tamaslim.com/js/bootstrap.min.js
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/js/bootstrap.min.js
# https://www.tamaslim.com/sit-to-fit/
# https://www.tamaslim.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
# https://www.tamaslim.com/contact/
# https://www.tamaslim.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
# https://www.tamaslim.com/careers/
# https://www.tamaslim.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
